@startuml ttt


stInstrWrite --> stRegFileWr : [*]
stInstrWrite : [instrWrite = 1]


stRegFileWr --> stPCUpdate : [*]
stRegFileWr : [regFileWr = 1]
 


stPCUpdate --> stInstrWrite : [*]
stPCUpdate : [floprPcUpdate = 1]
@enduml