@startuml ttt

state flopr_pc_inst {
    state PC_i
    state PC_o
}

state regfile {
    state rf_a0
    state rf_a1
    state rf_a2
    state rf_aw
    state rf_wd 
    state rf_r0 
    state rf_r1
    state rf_r2
}



state mem_inst {
    state mem_adr
    state mem_din
    state mem_dout
}



state flopr_i_inst {
    state fi_din
    state fi_dout
}




state fsm {
}


state alu_inst {
    state alu_0_i
    state alu_1_i
    state alu_2_i
    state ALUResult
}



state equal_regs {
    state eq_reg_0_i
    state eq_reg_1_i
    state r_equal
}

@enduml